# Generated by Django 5.2 on 2025-04-05 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIRECTORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=64)),
                ('dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.directory')),
            ],
        ),
        migrations.CreateModel(
            name='STL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=64)),
                ('icon', models.CharField(max_length=16)),
                ('prev', models.CharField(max_length=256)),
                ('dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.directory')),
            ],
        ),
    ]
