# Generated by Django 5.2 on 2025-05-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_directory_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='dirid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stl',
            name='dirid',
            field=models.IntegerField(null=True),
        ),
    ]
